name: HeroicDeath
main: com.herocraftonline.squallseed31.heroicdeath.HeroicDeath
version: 1.11.0
website: http://www.thedarktide.net
description: Minecraft plugin for Bukkit that announces player deaths.
author: SquallSeeD31